// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application";


import ConfirmationController from "./confirmation_controller.js";
application.register("confirmation", ConfirmationController);

import CounterController from "./counter_controller.js";
application.register("counter", CounterController);

import DropdownController from "./dropdown_controller.js";
application.register("dropdown", DropdownController);

import InfiniteScrollController from "./infinite_scroll_controller.js";
application.register("infinite-scroll", InfiniteScrollController);

import ModalController from "./modal_controller.js";
application.register("modal", ModalController);

import NavSearchController from "./nav_search_controller.js";
application.register("nav-search", NavSearchController);

import SelectController from "./select_controller.js";
application.register("select", SelectController);

import PopperController from "./popper_controller.js";
application.register("popper", PopperController);

import ToggleController from "./toggle_controller.js";
application.register("toggle", ToggleController);

import ShowMoreController from "./show_more_controller.js";
application.register("show-more", ShowMoreController);

import ShowContactController from "./show_contact_controller.js";
application.register("show-contact", ShowContactController);

import ChartController from "./chart_controller.js"
application.register("chart", ChartController)

import ShowGraphController from "./show_graph_controller.js"
application.register("show-graph", ShowGraphController)

import GraphController from "./graph_controller.js";
application.register("graph", GraphController);

import TooltipController from "./tooltip_controller.js";
application.register("tooltip", TooltipController);

import FollowupAfterController from "./followup_after_controller.js";
application.register("followup-after", FollowupAfterController);

import RatingGraphController from "./rating_graph_controller.js";
application.register("rating-graph", RatingGraphController);

import ConfirmationFetchController from "./confirmation_fetch_controller.js";
application.register("confirmation-fetch", ConfirmationFetchController);

import UserController from "./user_controller.js";
application.register("user", UserController);

import TaskController from "./task_controller.js";
application.register("task", TaskController);

import ContactController from "./contact_controller.js";
application.register("contact", ContactController);

