// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import ApplicationController from "./application_controller.js"
application.register("application", ApplicationController)

import ConfirmationController from "./confirmation_controller.js"
application.register("confirmation", ConfirmationController)

import DropdownController from "./dropdown_controller.js"
application.register("dropdown", DropdownController)

import ExampleController from "./example_controller.js"
application.register("example", ExampleController)

import HelloController from "./hello_controller.js"
application.register("hello", HelloController)

import InfiniteScrollController from "./infinite_scroll_controller.js"
application.register("infinite-scroll", InfiniteScrollController)

import ModalController from "./modal_controller.js"
application.register("modal", ModalController)



import NavSearchController from "./nav_search_controller.js"
import StimulusReflex from 'stimulus_reflex'
import consumer from '../channels/consumer'
import controller from '../controllers/application_controller'
import CableReady from 'cable_ready'
application.register("nav-search", NavSearchController)
application.consumer = consumer
StimulusReflex.initialize(application, { controller, isolate: true })
CableReady.initialize({ consumer })

