send_daily_reminders:
  cron: '0 10 * * * *'
  class: DailyReminderMailerJob
  queue: default
  description: 'This job sends a daily list of reminder to users 10:00 AM'

send_weekly_report:
  cron: '0 10 * * MON'
  class: WeeklyActivityCountMailerJob
  queue: default
  description: 'This job sends a weekly count of new added contacts count and pending followups count to users 10:00 AM'  